services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python main.py
    container_name: egor_bot
    volumes:
      - ./:/usr/src

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - bot
    command: alembic upgrade head
    container_name: egor_bot_migration
